/**
 * CompactBadge.tsx
 *
 * The smallest widget variant — designed for footers, email signatures,
 * sticky website bars, and any constrained space.
 *
 * Visual anatomy (single row, ~260 × 48 px):
 *   [Shield logo]  |  ★★★★½  4.8  ·  Verified on ReviewWise
 *
 * This is also the reference implementation for the standalone HTML
 * badge generated by the embed script, so styles intentionally use
 * only Tailwind utility classes (no external CSS variables).
 */

import { motion } from "framer-motion";
import { ShieldCheck } from "lucide-react";
import { Stars } from "./Stars";
import type { TrustWidgetProps } from "./types";

export const CompactBadge = ({
  slug,
  rating,
  reviewCount,
  profileUrl,
}: TrustWidgetProps) => {
  const href = profileUrl ?? `/biz/${slug}`;

  return (
    <motion.a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ scale: 1.02 }}
      transition={{ type: "spring", stiffness: 320, damping: 26 }}
      dir="rtl"
      className="group inline-flex items-center gap-2.5 rounded-xl border text-inherit no-underline cursor-pointer shrink-0"
      style={{
        padding: "8px 14px",
        background: "linear-gradient(135deg, hsl(0 0% 8% / 0.96), hsl(168 20% 6% / 0.96))",
        border: "1px solid hsl(168 45% 30% / 0.3)",
        boxShadow: "0 2px 12px hsl(0 0% 0% / 0.4), inset 0 1px 0 hsl(168 45% 60% / 0.07)",
        backdropFilter: "blur(12px)",
        WebkitBackdropFilter: "blur(12px)",
        minWidth: 220,
        maxWidth: 300,
      }}
    >
      {/* Shield icon */}
      <div
        className="shrink-0 flex items-center justify-center rounded-lg"
        style={{
          width: 30,
          height: 30,
          background: "hsl(168 45% 20% / 0.5)",
          border: "1px solid hsl(168 45% 40% / 0.3)",
        }}
      >
        <ShieldCheck size={16} strokeWidth={1.8} style={{ color: "hsl(168 55% 60%)" }} />
      </div>

      {/* Divider */}
      <div style={{ width: 1, height: 26, background: "hsl(0 0% 100% / 0.1)" }} />

      {/* Stars + score */}
      <div className="flex items-center gap-1.5 shrink-0">
        <span
          className="font-bold tabular-nums"
          style={{ color: "hsl(0 0% 97%)", fontSize: 15, lineHeight: 1 }}
        >
          {rating.toFixed(1)}
        </span>
        <Stars rating={rating} size={13} />
      </div>

      {/* Divider */}
      <div style={{ width: 1, height: 26, background: "hsl(0 0% 100% / 0.1)" }} />

      {/* Verified label */}
      <div className="flex flex-col leading-none min-w-0">
        <span
          className="font-semibold truncate"
          style={{ color: "hsl(168 55% 65%)", fontSize: 10, letterSpacing: "0.04em" }}
        >
          Verified Reviews
        </span>
        <span
          style={{ color: "hsl(0 0% 100% / 0.35)", fontSize: 9 }}
        >
          {reviewCount.toLocaleString("he-IL")} ביקורות
        </span>
      </div>
    </motion.a>
  );
};
